{**********************************************************************}
{                                                                      }
{                 This auxiliary unit was generated by                 }
{                 DevExpress Project Settings Manager.                 }
{                                                                      }
{  The dxSettings unit reflects the current project settings in        }
{  the source code of your project. Do not modify this file directly.  }
{                                                                      }
{  Use the DevExpress Project Settings dialog to configure all project }
{  settings related to DevExpress components. Select the following     }
{  item in the main menu of your RAD Studio IDE to invoke the dialog:  }
{                                                                      }
{            Project | DevExpress Settings for Your Project            }
{                                                                      }
{**********************************************************************}

unit ClassificacaoTriangulo.dxSettings;

interface

uses
  Winapi.Windows, System.Classes, Vcl.Themes, dxCore, cxLookAndFeels,
  dxSkinsCore, dxSkinsForm, dxSkinWXI, dxSkinTheBezier, dxSkinOffice2019Colorful,
  dxSkinOffice2019Black, dxSkinOffice2019DarkGray, dxSkinOffice2019White, dxSkinBasic, dxSkinBlack,
  dxSkinBlue, dxSkinBlueprint, dxSkinCaramel, dxSkinCoffee, dxSkinDarkroom,
  dxSkinDarkSide, dxSkinDevExpressDarkStyle, dxSkinDevExpressStyle, dxSkinFoggy, dxSkinGlassOceans,
  dxSkinHighContrast, dxSkiniMaginary, dxSkinLilian, dxSkinLiquidSky, dxSkinLondonLiquidSky,
  dxSkinMcSkin, dxSkinMetropolis, dxSkinMetropolisDark, dxSkinMoneyTwins, dxSkinOffice2007Black,
  dxSkinOffice2007Blue, dxSkinOffice2007Green, dxSkinOffice2007Pink, dxSkinOffice2007Silver, dxSkinOffice2010Black,
  dxSkinOffice2010Blue, dxSkinOffice2010Silver, dxSkinOffice2013DarkGray, dxSkinOffice2013LightGray, dxSkinOffice2013White,
  dxSkinOffice2016Colorful, dxSkinOffice2016Dark, dxSkinPumpkin, dxSkinSeven, dxSkinSevenClassic,
  dxSkinSharp, dxSkinSharpPlus, dxSkinSilver, dxSkinSpringtime, dxSkinStardust,
  dxSkinSummer2008, dxSkinTheAsphaltWorld, dxSkinValentine, dxSkinVisualStudio2013Blue, dxSkinVisualStudio2013Dark,
  dxSkinVisualStudio2013Light, dxSkinVS2010, dxSkinWhiteprint, dxSkinXmas2008Blue;

implementation

procedure LoadToRoot(ARoot: TcxRootLookAndFeel);
begin
  ARoot.Kind := lfUltraFlat;
  ARoot.NativeStyle := True;
  ARoot.ScrollbarMode := sbmDefault;
  ARoot.ScrollMode := scmDefault;
  ARoot.SkinName := 'WXICompact';
  ARoot.RenderMode := rmDefault;
  ARoot.TouchMode := False;
  ARoot.FormCorners := fcDefault;
  ARoot.SkinPaletteName := 'Default';
  ARoot.ShowFormShadow := bDefault;
  ARoot.UseSkins := True;
  ARoot.UseImageSet := imsDefault;
  ARoot.UseSkinsInPopupMenus := True;
  ARoot.UseGlobalSkin := True;
end;

procedure Load;
var
  ARoot: TcxRootLookAndFeel;
begin
{$IFDEF VER360}
  TStyleManager.ChangeChildFormSystemBorder := False;
{$ENDIF}
  cxProjectSettingsAreOverriding := True;
  cxCanUseSkinsWithoutSkinController := True;
  ARoot := TcxRootLookAndFeel.Instance;
  ARoot.BeginUpdate;
  try
    LoadToRoot(ARoot);
  finally
    ARoot.EndUpdate;
  end;
  TdxVisualRefinements.LightStyleMode := lsmOnlyBorders;
end;

initialization
  Load;
end.